name: casei_tutorias
description: Version movíl del sistema de gestion academica CACEI.
publish_to: 'none'
version: 0.1.0+11

environment:
  sdk: ^3.12.0-327.4.beta

dependencies:
  cupertino_icons: ^1.0.9
  device_preview: ^1.3.1
  firebase_core: ^4.11.0
  firebase_messaging: ^16.4.1
  flutter:
    sdk: flutter
  flutter_secure_storage: ^10.3.1
  go_router: ^17.3.0
  http: ^1.6.0
  provider: ^6.1.5+1
  shared_preferences: ^2.5.5
  supabase_flutter: ^2.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon_foreground.png"

flutter:
  uses-material-design: true
